apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: case1-join-demo
spec:
  params:
  - name: Token
    value: ""
  - name: Project_ID
    value: ""
  - name: Job_ID
    value: ""
  serviceAccountName: 'default'
  pipelineSpec:
    params:
    - name: Token
    - name: Project_ID
    - name: Job_ID
    tasks:
      - name: fork-join-activity1
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        taskSpec:
          params:
          - name: Token
          - name: Project_ID
          - name: Job_ID
          steps:
            - name: main
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: ["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"]
      - name: fork-join-activity2
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
          - fork-join-activity1
        taskSpec:
          params:
            - name: Token
            - name: Project_ID
            - name: Job_ID
          steps:
            - name: main
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: ["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"]
      - name: fork-join-activity3
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
          - fork-join-activity2
        taskSpec:
          params:
            - name: Token
            - name: Project_ID
            - name: Job_ID
          steps:
            - name: main
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: ["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"]
      - name: fork-join-activity4
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
          - fork-join-activity1
        taskSpec:
          params:
            - name: Token
            - name: Project_ID
            - name: Job_ID
          steps:
            - name: main
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: ["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"]
      - name: fork-join-activity5
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
          - fork-join-activity4
        taskSpec:
          params:
            - name: Token
            - name: Project_ID
            - name: Job_ID
          steps:
            - name: main
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: ["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"]
      - name: join-condition
        runAfter:
          - fork-join-activity3
          - fork-join-activity5
        taskSpec:
          steps:
            - name: main
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: ['echo This is join-condition...\n']
      - name: fork-join-activity6
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
          - join-condition
        taskSpec:
          params:
            - name: Token
            - name: Project_ID
            - name: Job_ID
          steps:
            - name: main
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: ["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"]
