apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"tekton.dev/v1beta1","kind":"PipelineRun","metadata":{"annotations":{},"name":"case3-disconnected-demo","namespace":"default"},"spec":{"params":[{"name":"Token","value":"eyJraWQiOiIyMDIwMTEyODE0NDkiLCJhbGciOiJSUzI1NiJ9.eyJpYW1faWQiOiJJQk1pZC01NTAwMDFXVDBHIiwiaWQiOiJJQk1pZC01NTAwMDFXVDBHIiwicmVhbG1pZCI6IklCTWlkIiwianRpIjoiN2ExMDMxNDQtNDAxMS00N2FiLWEyMzctYWVlMWRkNTc3OWY5IiwiaWRlbnRpZmllciI6IjU1MDAwMVdUMEciLCJnaXZlbl9uYW1lIjoiTWVuZyBKaWUiLCJmYW1pbHlfbmFtZSI6IkxpIiwibmFtZSI6Ik1lbmcgSmllIExpIiwiZW1haWwiOiJtZW5namllbGlAY24uaWJtLmNvbSIsInN1YiI6Im1lbmdqaWVsaUBjbi5pYm0uY29tIiwiYWNjb3VudCI6eyJ2YWxpZCI6dHJ1ZSwiYnNzIjoiZGIzYWEyMDU3OGQ0NDlmODhjYjY2ZDZkNmNlMmM5ODUiLCJmcm96ZW4iOnRydWV9LCJpYXQiOjE2MDY4MTQwMjAsImV4cCI6MTYwNjgxNzYyMCwiaXNzIjoiaHR0cHM6Ly9pYW0udGVzdC5jbG91ZC5pYm0uY29tL2lkZW50aXR5IiwiZ3JhbnRfdHlwZSI6InVybjppYm06cGFyYW1zOm9hdXRoOmdyYW50LXR5cGU6YXBpa2V5Iiwic2NvcGUiOiJpYm0gb3BlbmlkIiwiY2xpZW50X2lkIjoiZGVmYXVsdCIsImFjciI6MSwiYW1yIjpbInB3ZCJdfQ.NwSXrvdlHDjJYzZqkieOmC769Rt_uHJQtPIHYAti0wCUPHGQnBVTzW8ZxnLfa4h_dxQJjUsR9wPMZUva1gJbPfL3b0AUIOdHLGDQsOaSbuxu2gKNp2-qtUbsEjuI0ZMxFWGczgxxfYnA1cL4Xy-UyGikEe5IMPMx0nE0aG32sWOG0_xeVqvgJFvUGUpT4vrwMNdIIuVsQ0rREe2dzrGHIlQ3nQQ61_T6HXetM6QPjJ6J_Y_Qc4LNj88Nx2JvAtk2WKU_gWHkfECfgUFYUWVZOaSefcBHv5ylZwPrc3yYiqFynlM3LQRaVz5tTEanLlX3Ty-X3I4kHeCrgATh9EkZCQ"},{"name":"Project_ID","value":"2cf7dba3-440e-4916-8470-edc84df8816c"},{"name":"Job_ID","value":"43461a49-e310-42a1-8ad2-14dc53b5e04a"}],"pipelineSpec":{"params":[{"name":"Token"},{"name":"Project_ID"},{"name":"Job_ID"}],"tasks":[{"name":"disconnected-activity1","params":[{"name":"Token","value":"$(params.Token)"},{"name":"Project_ID","value":"$(params.Project_ID)"},{"name":"Job_ID","value":"$(params.Job_ID)"}],"taskSpec":{"params":[{"name":"Token"},{"name":"Project_ID"},{"name":"Job_ID"}],"steps":[{"args":["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"],"command":["/bin/bash","-c"],"image":"hejinchi/datastage:v0.41","imagePullPolicy":"IfNotPresent","name":"main","securityContext":{"runAsUser":0}}]}},{"name":"disconnected-activity2","params":[{"name":"Token","value":"$(params.Token)"},{"name":"Project_ID","value":"$(params.Project_ID)"},{"name":"Job_ID","value":"$(params.Job_ID)"}],"runAfter":["disconnected-activity1"],"taskSpec":{"params":[{"name":"Token"},{"name":"Project_ID"},{"name":"Job_ID"}],"steps":[{"args":["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"],"command":["/bin/bash","-c"],"image":"hejinchi/datastage:v0.41","imagePullPolicy":"IfNotPresent","name":"main","securityContext":{"runAsUser":0}}]}},{"name":"disconnected-activity3","params":[{"name":"Token","value":"$(params.Token)"},{"name":"Project_ID","value":"$(params.Project_ID)"},{"name":"Job_ID","value":"$(params.Job_ID)"}],"runAfter":["disconnected-activity2"],"taskSpec":{"params":[{"name":"Token"},{"name":"Project_ID"},{"name":"Job_ID"}],"steps":[{"args":["/datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)"],"command":["/bin/bash","-c"],"image":"hejinchi/datastage:v0.41","imagePullPolicy":"IfNotPresent","name":"main","securityContext":{"runAsUser":0}}]}}]},"serviceAccountName":"default"}}
    creationTimestamp: "2020-12-01T09:30:44Z"
    generation: 1
    labels:
      tekton.dev/pipeline: case3-disconnected-demo
    managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:params: {}
          f:pipelineSpec:
            .: {}
            f:params: {}
            f:tasks: {}
          f:serviceAccountName: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2020-12-01T09:30:44Z"
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:tekton.dev/pipeline: {}
        f:status:
          .: {}
          f:completionTime: {}
          f:conditions: {}
          f:pipelineSpec:
            .: {}
            f:params: {}
            f:tasks: {}
          f:startTime: {}
          f:taskRuns:
            .: {}
            f:case3-disconnected-demo-disconnected-activity1-mjbrk:
              .: {}
              f:pipelineTaskName: {}
              f:status:
                .: {}
                f:completionTime: {}
                f:conditions: {}
                f:podName: {}
                f:startTime: {}
                f:steps: {}
                f:taskSpec:
                  .: {}
                  f:params: {}
                  f:steps: {}
            f:case3-disconnected-demo-disconnected-activity2-vqvp9:
              .: {}
              f:pipelineTaskName: {}
              f:status:
                .: {}
                f:completionTime: {}
                f:conditions: {}
                f:podName: {}
                f:startTime: {}
                f:steps: {}
                f:taskSpec:
                  .: {}
                  f:params: {}
                  f:steps: {}
            f:case3-disconnected-demo-disconnected-activity3-l5z74:
              .: {}
              f:pipelineTaskName: {}
              f:status:
                .: {}
                f:completionTime: {}
                f:conditions: {}
                f:podName: {}
                f:startTime: {}
                f:steps: {}
                f:taskSpec:
                  .: {}
                  f:params: {}
                  f:steps: {}
      manager: controller
      operation: Update
      time: "2020-12-01T09:32:17Z"
    name: case3-disconnected-demo
    namespace: default
    resourceVersion: "147111"
    selfLink: /apis/tekton.dev/v1beta1/namespaces/default/pipelineruns/case3-disconnected-demo
    uid: ffa3d1b5-cc76-496f-a03d-f7d68a90f21f
  spec:
    params:
    - name: Token
      value: eyJraWQiOiIyMDIwMTEyODE0NDkiLCJhbGciOiJSUzI1NiJ9.eyJpYW1faWQiOiJJQk1pZC01NTAwMDFXVDBHIiwiaWQiOiJJQk1pZC01NTAwMDFXVDBHIiwicmVhbG1pZCI6IklCTWlkIiwianRpIjoiN2ExMDMxNDQtNDAxMS00N2FiLWEyMzctYWVlMWRkNTc3OWY5IiwiaWRlbnRpZmllciI6IjU1MDAwMVdUMEciLCJnaXZlbl9uYW1lIjoiTWVuZyBKaWUiLCJmYW1pbHlfbmFtZSI6IkxpIiwibmFtZSI6Ik1lbmcgSmllIExpIiwiZW1haWwiOiJtZW5namllbGlAY24uaWJtLmNvbSIsInN1YiI6Im1lbmdqaWVsaUBjbi5pYm0uY29tIiwiYWNjb3VudCI6eyJ2YWxpZCI6dHJ1ZSwiYnNzIjoiZGIzYWEyMDU3OGQ0NDlmODhjYjY2ZDZkNmNlMmM5ODUiLCJmcm96ZW4iOnRydWV9LCJpYXQiOjE2MDY4MTQwMjAsImV4cCI6MTYwNjgxNzYyMCwiaXNzIjoiaHR0cHM6Ly9pYW0udGVzdC5jbG91ZC5pYm0uY29tL2lkZW50aXR5IiwiZ3JhbnRfdHlwZSI6InVybjppYm06cGFyYW1zOm9hdXRoOmdyYW50LXR5cGU6YXBpa2V5Iiwic2NvcGUiOiJpYm0gb3BlbmlkIiwiY2xpZW50X2lkIjoiZGVmYXVsdCIsImFjciI6MSwiYW1yIjpbInB3ZCJdfQ.NwSXrvdlHDjJYzZqkieOmC769Rt_uHJQtPIHYAti0wCUPHGQnBVTzW8ZxnLfa4h_dxQJjUsR9wPMZUva1gJbPfL3b0AUIOdHLGDQsOaSbuxu2gKNp2-qtUbsEjuI0ZMxFWGczgxxfYnA1cL4Xy-UyGikEe5IMPMx0nE0aG32sWOG0_xeVqvgJFvUGUpT4vrwMNdIIuVsQ0rREe2dzrGHIlQ3nQQ61_T6HXetM6QPjJ6J_Y_Qc4LNj88Nx2JvAtk2WKU_gWHkfECfgUFYUWVZOaSefcBHv5ylZwPrc3yYiqFynlM3LQRaVz5tTEanLlX3Ty-X3I4kHeCrgATh9EkZCQ
    - name: Project_ID
      value: 2cf7dba3-440e-4916-8470-edc84df8816c
    - name: Job_ID
      value: 43461a49-e310-42a1-8ad2-14dc53b5e04a
    pipelineSpec:
      params:
      - name: Token
        type: string
      - name: Project_ID
        type: string
      - name: Job_ID
        type: string
      tasks:
      - name: disconnected-activity1
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        taskSpec:
          metadata: {}
          params:
          - name: Token
            type: string
          - name: Project_ID
            type: string
          - name: Job_ID
            type: string
          steps:
          - args:
            - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
            command:
            - /bin/bash
            - -c
            image: hejinchi/datastage:v0.41
            imagePullPolicy: IfNotPresent
            name: main
            resources: {}
            securityContext:
              runAsUser: 0
      - name: disconnected-activity2
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
        - disconnected-activity1
        taskSpec:
          metadata: {}
          params:
          - name: Token
            type: string
          - name: Project_ID
            type: string
          - name: Job_ID
            type: string
          steps:
          - args:
            - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
            command:
            - /bin/bash
            - -c
            image: hejinchi/datastage:v0.41
            imagePullPolicy: IfNotPresent
            name: main
            resources: {}
            securityContext:
              runAsUser: 0
      - name: disconnected-activity3
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
        - disconnected-activity2
        taskSpec:
          metadata: {}
          params:
          - name: Token
            type: string
          - name: Project_ID
            type: string
          - name: Job_ID
            type: string
          steps:
          - args:
            - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
            command:
            - /bin/bash
            - -c
            image: hejinchi/datastage:v0.41
            imagePullPolicy: IfNotPresent
            name: main
            resources: {}
            securityContext:
              runAsUser: 0
    serviceAccountName: default
    timeout: 1h0m0s
  status:
    completionTime: "2020-12-01T09:32:17Z"
    conditions:
    - lastTransitionTime: "2020-12-01T09:32:17Z"
      message: 'Tasks Completed: 3 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    pipelineSpec:
      params:
      - name: Token
        type: string
      - name: Project_ID
        type: string
      - name: Job_ID
        type: string
      tasks:
      - name: disconnected-activity1
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        taskSpec:
          metadata: {}
          params:
          - name: Token
            type: string
          - name: Project_ID
            type: string
          - name: Job_ID
            type: string
          steps:
          - args:
            - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
            command:
            - /bin/bash
            - -c
            image: hejinchi/datastage:v0.41
            imagePullPolicy: IfNotPresent
            name: main
            resources: {}
            securityContext:
              runAsUser: 0
      - name: disconnected-activity2
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
        - disconnected-activity1
        taskSpec:
          metadata: {}
          params:
          - name: Token
            type: string
          - name: Project_ID
            type: string
          - name: Job_ID
            type: string
          steps:
          - args:
            - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
            command:
            - /bin/bash
            - -c
            image: hejinchi/datastage:v0.41
            imagePullPolicy: IfNotPresent
            name: main
            resources: {}
            securityContext:
              runAsUser: 0
      - name: disconnected-activity3
        params:
        - name: Token
          value: $(params.Token)
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        runAfter:
        - disconnected-activity2
        taskSpec:
          metadata: {}
          params:
          - name: Token
            type: string
          - name: Project_ID
            type: string
          - name: Job_ID
            type: string
          steps:
          - args:
            - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
            command:
            - /bin/bash
            - -c
            image: hejinchi/datastage:v0.41
            imagePullPolicy: IfNotPresent
            name: main
            resources: {}
            securityContext:
              runAsUser: 0
    startTime: "2020-12-01T09:30:44Z"
    taskRuns:
      case3-disconnected-demo-disconnected-activity1-mjbrk:
        pipelineTaskName: disconnected-activity1
        status:
          completionTime: "2020-12-01T09:31:15Z"
          conditions:
          - lastTransitionTime: "2020-12-01T09:31:15Z"
            message: All Steps have completed executing
            reason: Succeeded
            status: "True"
            type: Succeeded
          podName: case3-disconnected-demo-disconnected-activity1-mjbrk-pod-f8lj9
          startTime: "2020-12-01T09:30:44Z"
          steps:
          - container: step-main
            imageID: docker.io/hejinchi/datastage@sha256:48b4c8f4f855b707b724d9eeee02422f2e6d9ffe491d6a042b81b316d435ef72
            name: main
            terminated:
              containerID: containerd://39bcd114221c8ed6c32799540db870f786888e861c24d6fa71d61abf02e44707
              exitCode: 0
              finishedAt: "2020-12-01T09:31:15Z"
              reason: Completed
              startedAt: "2020-12-01T09:30:47Z"
          taskSpec:
            params:
            - name: Token
              type: string
            - name: Project_ID
              type: string
            - name: Job_ID
              type: string
            steps:
            - args:
              - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
              command:
              - /bin/bash
              - -c
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              name: main
              resources: {}
              securityContext:
                runAsUser: 0
      case3-disconnected-demo-disconnected-activity2-vqvp9:
        pipelineTaskName: disconnected-activity2
        status:
          completionTime: "2020-12-01T09:31:48Z"
          conditions:
          - lastTransitionTime: "2020-12-01T09:31:48Z"
            message: All Steps have completed executing
            reason: Succeeded
            status: "True"
            type: Succeeded
          podName: case3-disconnected-demo-disconnected-activity2-vqvp9-pod-h779t
          startTime: "2020-12-01T09:31:15Z"
          steps:
          - container: step-main
            imageID: docker.io/hejinchi/datastage@sha256:48b4c8f4f855b707b724d9eeee02422f2e6d9ffe491d6a042b81b316d435ef72
            name: main
            terminated:
              containerID: containerd://95d3100cf32b133da4f11f1a417d4a235feec49d37e6a5189743c1881654c2cf
              exitCode: 0
              finishedAt: "2020-12-01T09:31:47Z"
              reason: Completed
              startedAt: "2020-12-01T09:31:19Z"
          taskSpec:
            params:
            - name: Token
              type: string
            - name: Project_ID
              type: string
            - name: Job_ID
              type: string
            steps:
            - args:
              - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
              command:
              - /bin/bash
              - -c
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              name: main
              resources: {}
              securityContext:
                runAsUser: 0
      case3-disconnected-demo-disconnected-activity3-l5z74:
        pipelineTaskName: disconnected-activity3
        status:
          completionTime: "2020-12-01T09:32:17Z"
          conditions:
          - lastTransitionTime: "2020-12-01T09:32:17Z"
            message: All Steps have completed executing
            reason: Succeeded
            status: "True"
            type: Succeeded
          podName: case3-disconnected-demo-disconnected-activity3-l5z74-pod-ptdxk
          startTime: "2020-12-01T09:31:48Z"
          steps:
          - container: step-main
            imageID: docker.io/hejinchi/datastage@sha256:48b4c8f4f855b707b724d9eeee02422f2e6d9ffe491d6a042b81b316d435ef72
            name: main
            terminated:
              containerID: containerd://08fca9de04524576bc41fd5419ac44e4c602d4bf2102017665e16d42ed3b3816
              exitCode: 0
              finishedAt: "2020-12-01T09:32:17Z"
              reason: Completed
              startedAt: "2020-12-01T09:31:51Z"
          taskSpec:
            params:
            - name: Token
              type: string
            - name: Project_ID
              type: string
            - name: Job_ID
              type: string
            steps:
            - args:
              - /datastage/dsRun $(params.Project_ID) $(params.Job_ID) $(params.Token)
              command:
              - /bin/bash
              - -c
              image: hejinchi/datastage:v0.41
              imagePullPolicy: IfNotPresent
              name: main
              resources: {}
              securityContext:
                runAsUser: 0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
