apiVersion: v1
kind: Pod
metadata:
  generateName: static-web-
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: "80m"
        limits:
          cpu: "80m"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
