apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: trigger-conditions10
spec:
  params:
    - name: Project_ID
      value: "2cf7dba3-440e-4916-8470-edc84df8816c"
    - name: Job_ID
      value: "43461a49-e310-42a1-8ad2-14dc53b5e04a"
    - name: Job_Execution_Action
      value: "Run"
    - name: Triggers_Execution_Type
      value: "OK"
    - name: Triggers_Expression
      value: ""
      #      description: "Must specify if Triggers_Execution_Type is Custom"
  serviceAccountName: 'default'
  pipelineSpec:
    params:
      - name: Project_ID
      - name: Job_ID
      - name: Triggers_Execution_Type
      - name: Job_Execution_Action
      - name: Triggers_Expression
    tasks:
      - name: conditions-activity
        params:
        - name: Project_ID
          value: $(params.Project_ID)
        - name: Job_ID
          value: $(params.Job_ID)
        - name: Triggers_Execution_Type
          value: $(params.Triggers_Execution_Type)
        - name: Job_Execution_Action
          value: $(params.Job_Execution_Action)
        - name: Triggers_Expression
          value: $(params.Triggers_Expression)
        taskSpec:
          params:
          - name: Project_ID
          - name: Job_ID
          - name: Triggers_Execution_Type
          - name: Job_Execution_Action
          - name: Triggers_Expression
          results:
          - name: run_id
          - name: state
          - name: continue
          steps:
            - name: main
              image: dspipelines/jobactivity:v0.41
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 0
              command: ["/bin/bash", "-c"]
              args: 
                - >-
                    python /dsRun.py
                    --project-id "$(params.Project_ID)"
                    --job-id "$(params.Job_ID)"
                    --exe-action "$(params.Job_Execution_Action)"
                    --expression-type "$(params.Triggers_Execution_Type)"
                    --expression "$(params.Triggers_Expression)"
                    --run-id-path "$(results.run_id.path)"
                    --state-path "$(results.state.path)"
                    --continue-path "$(results.continue.path)"
                    --api-key "1dJ8lm5mbzr024SMYSYBwkX8Cx9Y9eXHt8VqG9nOqVd8"
                    --get-logs False
